project:
  type: website

website:
  title: "Kangju Sun"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Posts

format:
  html:
    css: styles.css
    toc: true